FROM node:24-alpine
WORKDIR /bookplate

COPY package*.json .npmrc ./
COPY app/server/package*.json ./app/server/
COPY app/client/package*.json ./app/client/
COPY app/server/prisma ./app/server/prisma
RUN npm ci
RUN npm run prisma:generate -w app/server

EXPOSE 3000
CMD ["npm", "run", "dev"]
