FROM node:24-alpine
WORKDIR /hass-odps

COPY package*.json ./
COPY app/server/package*.json ./app/server/
COPY app/client/package*.json ./app/client/
RUN npm ci

EXPOSE 3000
CMD ["npm", "run", "dev"]
