import { createUseStyles, Theme } from '~/provider/theme';

export const useStyle = createUseStyles((theme: Theme) => ({
  root: {
    position: 'relative',
  },
  chipsContainer: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: theme.space.xs,
    padding: theme.space.md,
    fontSize: theme.fontSize.sm,
    backgroundColor: theme.color.bg.input,
    border: `1px solid ${theme.color.border.default}`,
    borderRadius: theme.radius.md,
    cursor: 'text',
    minHeight: '2.25rem',
    '&:focus-within': {
      borderColor: theme.color.border.focus,
    },
  },
  chip: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: theme.space.xxs,
    padding: `${theme.space.xs} ${theme.space.md}`,
    background: theme.color.chip.subject.bg,
    color: theme.color.chip.subject.text,
    border: `1px solid ${theme.color.chip.subject.border}`,
    borderRadius: theme.radius.sm,
    fontSize: theme.fontSize.sm,
    fontWeight: theme.fontWeight.medium,
    lineHeight: theme.lineHeight.tight,
  },
  chipRemove: {
    display: 'flex',
    alignItems: 'center',
    background: 'none',
    border: 'none',
    padding: 0,
    cursor: 'pointer',
    color: 'inherit',
    opacity: 0.5,
    lineHeight: 1,
    '&:hover': {
      opacity: 1,
      color: theme.color.danger.default,
    },
    '& > svg': {
      height: theme.fontSize.sm,
      width: theme.fontSize.sm,
    },
  },
  input: {
    border: 'none',
    outline: 'none',
    background: 'transparent',
    fontFamily: 'inherit',
    fontSize: 'inherit',
    color: theme.color.text.primary,
    flexGrow: 1,
    minWidth: '8rem',
    // padding: `0 ${theme.space.xs}`,
    // Keep font-size at the 16px floor on mobile so focusing it doesn't zoom iOS.
    [theme.breakpoint.mobile]: { fontSize: '1rem' },
  },
  dropdown: {
    position: 'absolute',
    top: '100%',
    left: 0,
    right: 0,
    marginTop: theme.space.xxs,
    padding: 0,
    listStyle: 'none',
    backgroundColor: theme.color.bg.input,
    border: `1px solid ${theme.color.border.default}`,
    borderRadius: theme.radius.md,
    boxShadow: theme.shadow.hoverLift,
    zIndex: theme.zIndex.sticky,
    maxHeight: '12rem',
    overflowY: 'auto',
  },
  dropdownItem: {
    padding: `${theme.space.md} ${theme.space.xl}`,
    cursor: 'pointer',
    fontSize: theme.fontSize.md,
    color: theme.color.text.primary,
    '&:hover': {
      backgroundColor: theme.color.bg.cardHeader,
    },
    '&$highlighted': {
      backgroundColor: theme.color.brand.light,
    },
  },
  highlighted: {},
}));
