import './book';
import './config';
import './cover-fit';
import './device';
import './identifier';
import './library';
import './library-entry';
import './lineage-type';
import './linked-document';
import './metadata-fix';
import './pending-fix';
import './pending-fix-state';
import './pending-fix-summary';
import './progress';
import './series';
import './suggestion';
import './suggestion-group';
import './suggestion-type';
import './undo-kind';
import './undo-snapshot';
import './user';
import './validation';
import './validation-message';
import './validation-severity';
import './validation-threshold';
import './viewer';
import { builder } from './builder';

export const schema = builder.toSchema();
